#+TITLE:     password-menu.el
#+AUTHOR:    Robert Nadler
#+EMAIL:     robert.nadler@gmail.com

[[https://melpa.org/#/elfeed-curate][file:https://melpa.org/packages/password-menu-badge.svg]]  [[https://github.com/rnadler/password-menu/actions/workflows/melpazoid.yml/badge.svg]]

* Description :unfold:

*password-menu* is a UI wrapper for the built-in Emacs [[https://www.gnu.org/software/emacs/manual/html_mono/auth.html][auth-source]] library.
This package allows you to display auth-source entries in the minibuffer with
either =completing-read= or =transient=. The password for the selected entry is
copied to the kill ring and system clipboard and automatically removed later.

* Installation

If you use MELPA, an easy way to install this package is via
=package-install=. Alternatively, download =password-menu.el=, put it in
your =load-path= and =require= it.

If you use both MELPA and =use-package=, you can use this, too:

#+begin_src emacs-lisp
(use-package password-menu
  :ensure t)
#+end_src

** Custom key bindings

#+begin_src emacs-lisp
(global-set-key (kbd "C-x j") 'password-menu-transient)
(global-set-key (kbd "C-x J") 'password-menu-completing-read)
#+end_src

** [[https://github.com/doomemacs/doomemacs][Doom]] configuration

*** =packages.el=
#+begin_src emacs-lisp
;;...
(package! password-menu)
;;...
#+end_src
*** Key bindings
These can be added to =config.el= as shown above.

** Disclaimers

- I have only tested this with Emacs 29.1.
- Testing of the auth-sources backends was limited to only authinfo.pgp.

* Usage

** Password menus

*** Transient menu

This uses the keyboard selection of entries. Since the prefix ordering always
matches that of the source, this method is better suited for discreet key
sequences, for example =C-x j 3=.

*** Completing read menu

Entries are found by scrolling through or searching the list. This is likely
preferable when the list is long.


* Customization

Here are the variables that can be customized:

| Variable                                      | Default              | Desc.                                                     |
|-----------------------------------------------+----------------------+-----------------------------------------------------------|
| =password-menu-time-before-clipboard-restore= | 45                   | Number of seconds to wait before restoring the clipboard. |
| =password-menu-prompt=                        | "Get password for: " | Menu prompt string.                                       |
